sudo: false
rvm:
  - 2.4.0
notifications:
  email:
    recipients:
      - okkez000@gmail.com
      - zn@mbf.nifty.com
  irc:
    channels:
      - "chat.freenode.net#ruby-ja"
    on_success: change # [always|never|change] # default: always
    on_failure: always # [always|never|change] # default: always
    template:
      - "%{message} by @%{author}: See %{build_url}"
