language: ruby
dist: bionic
rvm:
  - 2.7.0 # docs.ruby-lang.org use ruby 2.7.0
notifications:
  email:
    recipients:
      - okkez000@gmail.com
      - kzhr.nsym@gmail.com
  irc:
    channels:
      - "chat.freenode.net#ruby-ja"
    on_success: change # [always|never|change] # default: always
    on_failure: always # [always|never|change] # default: always
    template:
      - "%{message} by @%{author}: See %{build_url}"
before_install:
  - 'go get github.com/client9/misspell/...'
script:
  - 'bundle exec rake'
  - 'git ls-files -z | xargs -0 $GOPATH/bin/misspell -error -i addopt'
