# usage:
#
# docker-compose build
# docker-compose run --rm rurema rake -T
# docker-compose run --rm rurema rake generate:2.7.0 statichtml:2.7.0
# open _site/2.7.0/index.html instead of /tmp/html/2.7.0/index.html

version: '2'
services:
  rurema:
    build: .
    volumes:
    - "./_site/:/tmp/html/"
    - "./Gemfile:/rurema/doctree/Gemfile"
    - "./Rakefile:/rurema/doctree/Rakefile"
    - "./refm:/rurema/doctree/refm"
