[build]
publish = "_site"
command = "env HTML_DIRECTORY_BASE=_site CI=netlify bundle exec rake statichtml:preview"

[[headers]]
  for = "/*"

  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/"
  to = "/2.7.0/doc/index.html"
